# Exploratory Data Analysis
Team: Anvith Mulpuri, Ansh Pathapati, Sahana Subramanyam, Akhila Arhla, Raahim Jawad

Dataset: https://apps.who.int/nha/database/Select/Indicators/en

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Data_Table 1.csv")
df

/var/folders/qq/qybk1kgs5xb3qkzmrn3x53qh0000gn/T/ipykernel_75094/3756995087.py:1: DtypeWarning: Columns (6,19,20,21,22,33,100,106,123,124,125,130,142,148,150,154,159,160,161,162,165,166,167,173,197,198,199,203,204,205,206,208,209,210,213,221,225,235,238,239,241,242,243,244,249,250,252,253,254,256,257,258,261,263,264,265,269,270,271,272,273,278,288,293,294,295,296,298,300,301,302,304,305,306,309,310,311,312,315,316,317,318,319,320,321,328,333,334,339,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,399,400,401,402,403,404,405,414,422,440,441,466,467,468,469,471,472,473,474,475,479,480,481,482,483,489,492,495,496,497,500,504,507,509,510,511,512,514,515,516,517,519,520,521,522,523,524,526,527,528,529,532,533,534,535,536,538,541,542,543,544,549,550,554,556,558,560,562,574,575,578,579,584,586,587,590,591,593,595,598,599,633,653,654,656,658,670,671,673,676,677,679,680,681,686,689,690,692,694,695,697,698,699,700,702,703,704,708,710,711,712,713,714,716,719,720,725,726,727,728,729,744,745,746,747,748,750,751,752,757,758,759,760,761,762,763,764,765,766,769,770,772,776,778,779,780,781,782,785,787,789,791,796,797,801,804,805,806,808,809,812,813,814,815,816,818,830,836,837,844,846,855,863,872,874,877,878,879,880,881,884,885,886,887,889,890,891,892,895,896,897,903,907,920,924,927,928,929,932,934,935,936,938,939,940,942,943,946,947,949,951,952,953,954,955,959,965,966,967,969,971,973,974,979,980,985,986,987,989,990,991,993,994,995,997,998,999) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Data_Table 1.csv")

,location,code,region,income,year,che_gdp,che_pc_usd,che,gghed,pvtd,...,hc51_ext_ncu_pc,hc511_ext_ncu_pc,hc512_ext_ncu_pc,hc513_ext_ncu_pc,hc52_ext_ncu_pc,hc5nec_ext_ncu_pc,hc6_ext_ncu_pc,hc61_ext_ncu_pc,hc62_ext_ncu_pc,fp3214_ext_ncu_pc
0,Algeria,DZA,AFR,Upper-middle,2000,3.2,62,"143,870","103,534","40,261",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Algeria,DZA,AFR,Upper-middle,2001,3.5,67,"162,231","123,664","38,492",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Algeria,DZA,AFR,Upper-middle,2002,3.4,67,"168,702","126,997","41,630",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,DZA,AFR,Upper-middle,2003,3.3,76,"189,137","145,057","43,985",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Algeria,DZA,AFR,Upper-middle,2004,3.3,93,"217,929","155,500","62,327",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4607,Viet Nam,VNM,WPR,Lower-middle,2019,5.0,171,"383,361,920","155,721,575","223,880,400",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4608,Viet Nam,VNM,WPR,Lower-middle,2020,4.3,153,"348,498,752","144,046,531","198,600,896",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4609,Viet Nam,VNM,WPR,Lower-middle,2021,4.5,168,"385,155,232","166,379,650","214,197,904",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4610,Viet Nam,VNM,WPR,Lower-middle,2022,4.5,188,"436,627,072","189,599,779","240,079,456",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4611,Viet Nam,VNM,WPR,Lower-middle,2023,4.6,197,"470,719,168","208,542,770","256,781,504",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print("Number of rows:", len(df))

Number of rows: 4612

In [4]:
print("Number of columns:", len(df.columns))

Number of columns: 1000

In [5]:
print("Names of columns:" , df.columns)

Names of columns: Index(['location', 'code', 'region', 'income', 'year', 'che_gdp', 'che_pc_usd',
       'che', 'gghed', 'pvtd',
       ...
       'hc51_ext_ncu_pc', 'hc511_ext_ncu_pc', 'hc512_ext_ncu_pc',
       'hc513_ext_ncu_pc', 'hc52_ext_ncu_pc', 'hc5nec_ext_ncu_pc',
       'hc6_ext_ncu_pc', 'hc61_ext_ncu_pc', 'hc62_ext_ncu_pc',
       'fp3214_ext_ncu_pc'],
      dtype='object', length=1000)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4612 entries, 0 to 4611
Columns: 1000 entries, location to fp3214_ext_ncu_pc
dtypes: float64(250), int64(2), object(748)
memory usage: 35.2+ MB

In [7]:
(df.isna().sum() / len(df)) * 100

location              0.000000
code                  0.000000
region                0.000000
income                0.000000
year                  0.000000
                       ...
hc5nec_ext_ncu_pc    96.248916
hc6_ext_ncu_pc       91.543799
hc61_ext_ncu_pc      93.061578
hc62_ext_ncu_pc      93.169991
fp3214_ext_ncu_pc    99.002602
Length: 1000, dtype: float64

In [9]:
df["region"].dropna().unique().tolist()

['AFR', 'AMR', 'EMR', 'EUR', 'SEAR', 'WPR']

In [10]:
df_amr = df[df["region"] == "AMR"]
df_amr

,location,code,region,income,year,che_gdp,che_pc_usd,che,gghed,pvtd,...,hc51_ext_ncu_pc,hc511_ext_ncu_pc,hc512_ext_ncu_pc,hc513_ext_ncu_pc,hc52_ext_ncu_pc,hc5nec_ext_ncu_pc,hc6_ext_ncu_pc,hc61_ext_ncu_pc,hc62_ext_ncu_pc,fp3214_ext_ncu_pc
1101,Antigua and Barbuda,ATG,AMR,High,2000,4.3,520,105,61,44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1102,Antigua and Barbuda,ATG,AMR,High,2001,5.0,572,118,69,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103,Antigua and Barbuda,ATG,AMR,High,2002,4.8,559,116,68,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1104,Antigua and Barbuda,ATG,AMR,High,2003,5.0,614,129,77,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1105,Antigua and Barbuda,ATG,AMR,High,2004,4.6,598,127,74,53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1921,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2019,2.2,113,9,3,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1922,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2020,4.1,153,245,91,154,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1923,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2021,4.1,162,"3,219","1,079","2,125",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1924,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2022,4.6,209,"12,185","5,530","6,569",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1925,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2023,3.8,186,"45,674","14,493","30,936",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_amr = df_amr.loc[:, (df_amr.isna().sum() / len(df_amr)) * 100 <= 70]

In [14]:
df_amr.shape

(825, 173)

In [15]:
df_amr

,location,code,region,income,year,che_gdp,che_pc_usd,che,gghed,pvtd,...,hf12nec_ncu_pc,hf13_ncu_pc,hf1nec_ncu_pc,hf2_ncu_pc,hf21_ncu_pc,hf22_ncu_pc,hf23_ncu_pc,hf2nec_ncu_pc,hf3_ncu_pc,hfnec_ncu_pc
1101,Antigua and Barbuda,ATG,AMR,High,2000,4.3,520,105,61,44,...,0.0,0.0,NaN,275,275,0,NaN,0.0,312,0
1102,Antigua and Barbuda,ATG,AMR,High,2001,5.0,572,118,69,48,...,0.0,0.0,NaN,280,280,0,NaN,0.0,351,0
1103,Antigua and Barbuda,ATG,AMR,High,2002,4.8,559,116,68,48,...,0.0,0.0,NaN,282,282,0,NaN,0.0,343,0
1104,Antigua and Barbuda,ATG,AMR,High,2003,5.0,614,129,77,52,...,0.0,0.0,NaN,280,280,0,NaN,0.0,385,0
1105,Antigua and Barbuda,ATG,AMR,High,2004,4.6,598,127,74,53,...,0.0,0.0,NaN,285,284,1,NaN,0.0,392,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1921,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2019,2.2,113,9,3,6,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
1922,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2020,4.1,153,245,91,154,...,0.0,0.0,0.0,3,3,0,0,0.0,2,0
1923,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2021,4.1,162,"3,219","1,079","2,125",...,0.0,0.0,0.0,44,43,1,0,0.0,32,0
1924,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2022,4.6,209,"12,185","5,530","6,569",...,0.0,0.0,0.0,128,125,3,0,0.0,107,0
1925,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2023,3.8,186,"45,674","14,493","30,936",...,0.0,0.0,0.0,623,613,9,0,0.0,479,0

In [18]:
df_amr.columns.tolist()

['location',
 'code',
 'region',
 'income',
 'year',
 'che_gdp',
 'che_pc_usd',
 'che',
 'gghed',
 'pvtd',
 'ext',
 'dom_che',
 'gghed_che',
 'pvtd_che',
 'oops_che',
 'vpp_che',
 'ext_che',
 'gghed_gdp',
 'gghed_gge',
 'gghed_pc_usd',
 'pvtd_pc_usd',
 'oop_pc_usd',
 'ext_pc_usd',
 'tran_shi',
 'shise_shi',
 'cfa_che',
 'gfa_che',
 'chi_che',
 'shi_che',
 'chi_pvt_che',
 'vfa_che',
 'vhi_che',
 'gge_gdp',
 'gdp_pc_usd',
 'fs',
 'fs1',
 'fs11',
 'fs12',
 'fs13',
 'fs14',
 'fs2',
 'fs3',
 'fs31',
 'fs32',
 'fs33',
 'fs34',
 'fs4',
 'fs5',
 'fs6',
 'fs61',
 'fs62',
 'fs63',
 'fs6nec',
 'fs7',
 'fsnec',
 'hf',
 'hf1',
 'hf11',
 'hf12',
 'hf121',
 'hf122',
 'hf12nec',
 'hf13',
 'hf1nec',
 'hf2',
 'hf21',
 'hf22',
 'hf23',
 'hf2nec',
 'hf3',
 'hfnec',
 'hk',
 'hk1',
 'hk11',
 'hk_gghed',
 'hk_ext',
 'gdp',
 'pfc',
 'gge',
 'ppp',
 'xrt',
 'gdpd',
 'pop',
 'che_usd',
 'gghed_usd',
 'pvtd_usd',
 'ext_usd',
 'fs_usd',
 'fs1_usd',
 'fs11_usd',
 'fs12_usd',
 'fs13_usd',
 'fs14_usd',
 'fs2_usd',
 'fs3_usd',
 'fs31_usd',
 'fs32_usd',
 'fs33_usd',
 'fs34_usd',
 'fs4_usd',
 'fs5_usd',
 'fs6_usd',
 'fs61_usd',
 'fs62_usd',
 'fs63_usd',
 'fs6nec_usd',
 'fs7_usd',
 'fsnec_usd',
 'hf_usd',
 'hf1_usd',
 'hf11_usd',
 'hf12_usd',
 'hf121_usd',
 'hf122_usd',
 'hf12nec_usd',
 'hf13_usd',
 'hf1nec_usd',
 'hf2_usd',
 'hf21_usd',
 'hf22_usd',
 'hf23_usd',
 'hf2nec_usd',
 'hf3_usd',
 'hfnec_usd',
 'hk_usd',
 'hk1_usd',
 'hk11_usd',
 'hk_gghed_usd',
 'hk_ext_usd',
 'gdp_usd',
 'pfc_usd',
 'gge_usd',
 'che_ncu_pc',
 'gghed_ncu_pc',
 'pvtd_ncu_pc',
 'ext_ncu_pc',
 'fs_ncu_pc',
 'fs1_ncu_pc',
 'fs11_ncu_pc',
 'fs12_ncu_pc',
 'fs13_ncu_pc',
 'fs14_ncu_pc',
 'fs2_ncu_pc',
 'fs3_ncu_pc',
 'fs31_ncu_pc',
 'fs32_ncu_pc',
 'fs33_ncu_pc',
 'fs34_ncu_pc',
 'fs4_ncu_pc',
 'fs5_ncu_pc',
 'fs6_ncu_pc',
 'fs61_ncu_pc',
 'fs62_ncu_pc',
 'fs63_ncu_pc',
 'fs6nec_ncu_pc',
 'fs7_ncu_pc',
 'fsnec_ncu_pc',
 'hf_ncu_pc',
 'hf1_ncu_pc',
 'hf11_ncu_pc',
 'hf12_ncu_pc',
 'hf121_ncu_pc',
 'hf122_ncu_pc',
 'hf12nec_ncu_pc',
 'hf13_ncu_pc',
 'hf1nec_ncu_pc',
 'hf2_ncu_pc',
 'hf21_ncu_pc',
 'hf22_ncu_pc',
 'hf23_ncu_pc',
 'hf2nec_ncu_pc',
 'hf3_ncu_pc',
 'hfnec_ncu_pc']

In [ ]:
col_rename = {
    'che_gdp': 'Health Expenditure % of GDP',
    'che_pc_usd': 'Health Expenditure Per Capita (USD)',
    'che': 'Current Health Expenditure (Local Currency)',
    'gghed': 'Govt Health Expenditure (Local Currency)',
    'pvtd': 'Private Health Expenditure (Local Currency)',
    'ext': 'External Health Aid (Local Currency)',
    'dom_che': 'Domestic Health Expenditure (Local Currency)',
    'gghed_che': 'Govt Share of Health Expenditure (%)',
    'pvtd_che': 'Private Share of Health Expenditure (%)',
    'oops_che': 'Out-of-Pocket Share of Health Expenditure (%)',
    'vpp_che': 'Voluntary Prepayment Share of Health Expenditure (%)',
    'ext_che': 'External Aid Share of Health Expenditure (%)',
    'gghed_gdp': 'Govt Health Expenditure % of GDP',
    'gghed_gge': 'Govt Health Expenditure % of Total Govt Expenditure',
    'gghed_pc_usd': 'Govt Health Expenditure Per Capita (USD)',
    'pvtd_pc_usd': 'Private Health Expenditure Per Capita (USD)',
    'oop_pc_usd': 'Out-of-Pocket Expenditure Per Capita (USD)',
    'ext_pc_usd': 'External Aid Per Capita (USD)',
    'tran_shi': 'Transfers to Social Health Insurance % of SHI Revenue',
    'shise_shi': 'Social Health Insurance Statutory Entitlement Share (%)',
    'cfa_che': 'Compulsory Financing Share of Health Expenditure (%)',
    'gfa_che': 'Govt Financing Arrangements Share of Health Expenditure (%)',
    'chi_che': 'Compulsory Health Insurance Share of Health Expenditure (%)',
    'shi_che': 'Social Health Insurance Share of Health Expenditure (%)',
    'chi_pvt_che': 'Compulsory Private Insurance Share of Health Expenditure (%)',
    'vfa_che': 'Voluntary Financing Share of Health Expenditure (%)',
    'vhi_che': 'Voluntary Health Insurance Share of Health Expenditure (%)',
    'gge_gdp': 'General Govt Expenditure % of GDP',
    'gdp_pc_usd': 'GDP Per Capita (USD)',
    'fs': 'Total Expenditure by Financing Source (Local Currency)',
    'fs1': 'Govt & Compulsory Contributory Financing (Local Currency)',
    'fs11': 'Govt Health Schemes / Tax-Funded (Local Currency)',
    'fs12': 'Compulsory Contributory Health Insurance (Local Currency)',
    'fs13': 'Compulsory Medical Savings Accounts (Local Currency)',
    'fs14': 'Other Compulsory Contributory Schemes (Local Currency)',
    'fs2': 'Voluntary Health Insurance (Local Currency)',
    'fs3': 'Out-of-Pocket Payments (Local Currency)',
    'fs31': 'OOP Cost-Sharing / Co-Pays (Local Currency)',
    'fs32': 'OOP Self-Medication / Direct Purchase (Local Currency)',
    'fs33': 'OOP Informal Payments (Local Currency)',
    'fs34': 'OOP Other Household Payments (Local Currency)',
    'fs4': 'Non-Profit Organisation Schemes (Local Currency)',
    'fs5': 'Enterprise / Employer Financing (Local Currency)',
    'fs6': 'External Aid Total (Local Currency)',
    'fs61': 'External Aid Grants (Local Currency)',
    'fs62': 'External Aid Loans (Local Currency)',
    'fs63': 'External Aid Other Transfers (Local Currency)',
    'fs6nec': 'External Aid Not Elsewhere Classified (Local Currency)',
    'fs7': 'Rest-of-World Financing (Local Currency)',
    'fsnec': 'Other Financing Sources NEC (Local Currency)',
    'hf': 'Total Expenditure by Financing Agent (Local Currency)',
    'hf1': 'Central/Federal Govt Health Authority (Local Currency)',
    'hf11': 'Central Govt Ministry of Health (Local Currency)',
    'hf12': 'State/Regional Govt Health Authority (Local Currency)',
    'hf121': 'State-Level Social Health Insurance Fund (Local Currency)',
    'hf122': 'Other State/Regional Govt Health Authority (Local Currency)',
    'hf12nec': 'State-Level Health Authority NEC (Local Currency)',
    'hf13': 'Local Govt Health Authority (Local Currency)',
    'hf1nec': 'Other Public Health Authority NEC (Local Currency)',
    'hf2': 'Social Health Insurance Funds (Local Currency)',
    'hf21': 'Social Health Insurance OECD-Type Fund (Local Currency)',
    'hf22': 'Other Social Health Insurance Fund (Local Currency)',
    'hf23': 'Compulsory Private Insurance Fund (Local Currency)',
    'hf2nec': 'Social / Compulsory Insurance NEC (Local Currency)',
    'hf3': 'Voluntary Health Insurance (Local Currency)',
    'hfnec': 'Financing Agent NEC (Local Currency)',
    'hk': 'Health Workforce Compensation Total (Local Currency)',
    'hk1': 'Health Employee Compensation (Local Currency)',
    'hk11': 'Doctors & Dentists Compensation (Local Currency)',
    'hk_gghed': 'Govt-Funded Workforce Compensation (Local Currency)',
    'hk_ext': 'Externally-Funded Workforce Compensation (Local Currency)',
    'gdp': 'GDP (Local Currency)',
    'pfc': 'Private Final Consumption (Local Currency)',
    'gge': 'General Govt Expenditure (Local Currency)',
    'ppp': 'Purchasing Power Parity Conversion Factor',
    'xrt': 'Exchange Rate (Local Currency per USD)',
    'gdpd': 'GDP Deflator (Price Index)',
    'pop': 'Total Population',
    # USD versions
    'che_usd': 'Current Health Expenditure (USD)',
    'gghed_usd': 'Govt Health Expenditure (USD)',
    'pvtd_usd': 'Private Health Expenditure (USD)',
    'ext_usd': 'External Health Aid (USD)',
    'fs_usd': 'Total Expenditure by Financing Source (USD)',
    'fs1_usd': 'Govt & Compulsory Contributory Financing (USD)',
    'fs11_usd': 'Govt Health Schemes Tax-Funded (USD)',
    'fs12_usd': 'Compulsory Contributory Health Insurance (USD)',
    'fs13_usd': 'Compulsory Medical Savings Accounts (USD)',
    'fs14_usd': 'Other Compulsory Contributory Schemes (USD)',
    'fs2_usd': 'Voluntary Health Insurance (USD)',
    'fs3_usd': 'Out-of-Pocket Payments (USD)',
    'fs31_usd': 'OOP Cost-Sharing (USD)',
    'fs32_usd': 'OOP Self-Medication (USD)',
    'fs33_usd': 'OOP Informal Payments (USD)',
    'fs34_usd': 'OOP Other Household Payments (USD)',
    'fs4_usd': 'Non-Profit Organisation Schemes (USD)',
    'fs5_usd': 'Enterprise Financing (USD)',
    'fs6_usd': 'External Aid Total (USD)',
    'fs61_usd': 'External Aid Grants (USD)',
    'fs62_usd': 'External Aid Loans (USD)',
    'fs63_usd': 'External Aid Other Transfers (USD)',
    'fs6nec_usd': 'External Aid NEC (USD)',
    'fs7_usd': 'Rest-of-World Financing (USD)',
    'fsnec_usd': 'Other Financing Sources NEC (USD)',
    'hf_usd': 'Total Expenditure by Financing Agent (USD)',
    'hf1_usd': 'Central/Federal Govt Health Authority (USD)',
    'hf11_usd': 'Central Govt Ministry of Health (USD)',
    'hf12_usd': 'State/Regional Govt Health Authority (USD)',
    'hf121_usd': 'State-Level Social Health Insurance Fund (USD)',
    'hf122_usd': 'Other State/Regional Govt Health Authority (USD)',
    'hf12nec_usd': 'State-Level Health Authority NEC (USD)',
    'hf13_usd': 'Local Govt Health Authority (USD)',
    'hf1nec_usd': 'Other Public Health Authority NEC (USD)',
    'hf2_usd': 'Social Health Insurance Funds (USD)',
    'hf21_usd': 'Social Health Insurance OECD-Type Fund (USD)',
    'hf22_usd': 'Other Social Health Insurance Fund (USD)',
    'hf23_usd': 'Compulsory Private Insurance Fund (USD)',
    'hf2nec_usd': 'Social / Compulsory Insurance NEC (USD)',
    'hf3_usd': 'Voluntary Health Insurance (USD)',
    'hfnec_usd': 'Financing Agent NEC (USD)',
    'hk_usd': 'Health Workforce Compensation Total (USD)',
    'hk1_usd': 'Health Employee Compensation (USD)',
    'hk11_usd': 'Doctors & Dentists Compensation (USD)',
    'hk_gghed_usd': 'Govt-Funded Workforce Compensation (USD)',
    'hk_ext_usd': 'Externally-Funded Workforce Compensation (USD)',
    'gdp_usd': 'GDP (USD)',
    'pfc_usd': 'Private Final Consumption (USD)',
    'gge_usd': 'General Govt Expenditure (USD)',
    # Per capita local currency versions
    'che_ncu_pc': 'Current Health Expenditure Per Capita (Local Currency)',
    'gghed_ncu_pc': 'Govt Health Expenditure Per Capita (Local Currency)',
    'pvtd_ncu_pc': 'Private Health Expenditure Per Capita (Local Currency)',
    'ext_ncu_pc': 'External Health Aid Per Capita (Local Currency)',
    'fs_ncu_pc': 'Total Financing Source Per Capita (Local Currency)',
    'fs1_ncu_pc': 'Govt & Compulsory Financing Per Capita (Local Currency)',
    'fs11_ncu_pc': 'Govt Health Schemes Per Capita (Local Currency)',
    'fs12_ncu_pc': 'Compulsory Health Insurance Per Capita (Local Currency)',
    'fs13_ncu_pc': 'Compulsory Savings Accounts Per Capita (Local Currency)',
    'fs14_ncu_pc': 'Other Compulsory Schemes Per Capita (Local Currency)',
    'fs2_ncu_pc': 'Voluntary Health Insurance Per Capita (Local Currency)',
    'fs3_ncu_pc': 'Out-of-Pocket Payments Per Capita (Local Currency)',
    'fs31_ncu_pc': 'OOP Cost-Sharing Per Capita (Local Currency)',
    'fs32_ncu_pc': 'OOP Self-Medication Per Capita (Local Currency)',
    'fs33_ncu_pc': 'OOP Informal Payments Per Capita (Local Currency)',
    'fs34_ncu_pc': 'OOP Other Payments Per Capita (Local Currency)',
    'fs4_ncu_pc': 'Non-Profit Schemes Per Capita (Local Currency)',
    'fs5_ncu_pc': 'Enterprise Financing Per Capita (Local Currency)',
    'fs6_ncu_pc': 'External Aid Per Capita (Local Currency)',
    'fs61_ncu_pc': 'External Aid Grants Per Capita (Local Currency)',
    'fs62_ncu_pc': 'External Aid Loans Per Capita (Local Currency)',
    'fs63_ncu_pc': 'External Aid Other Transfers Per Capita (Local Currency)',
    'fs6nec_ncu_pc': 'External Aid NEC Per Capita (Local Currency)',
    'fs7_ncu_pc': 'Rest-of-World Financing Per Capita (Local Currency)',
    'fsnec_ncu_pc': 'Other Financing NEC Per Capita (Local Currency)',
    'hf_ncu_pc': 'Total Financing Agent Per Capita (Local Currency)',
    'hf1_ncu_pc': 'Central Govt Health Authority Per Capita (Local Currency)',
    'hf11_ncu_pc': 'Ministry of Health Per Capita (Local Currency)',
    'hf12_ncu_pc': 'State/Regional Health Authority Per Capita (Local Currency)',
    'hf121_ncu_pc': 'State SHI Fund Per Capita (Local Currency)',
    'hf122_ncu_pc': 'Other State Health Authority Per Capita (Local Currency)',
    'hf12nec_ncu_pc': 'State Health Authority NEC Per Capita (Local Currency)',
    'hf13_ncu_pc': 'Local Govt Health Authority Per Capita (Local Currency)',
    'hf1nec_ncu_pc': 'Other Public Health Authority NEC Per Capita (Local Currency)',
    'hf2_ncu_pc': 'Social Health Insurance Funds Per Capita (Local Currency)',
    'hf21_ncu_pc': 'Social Health Insurance OECD-Type Per Capita (Local Currency)',
    'hf22_ncu_pc': 'Other Social Health Insurance Per Capita (Local Currency)',
    'hf23_ncu_pc': 'Compulsory Private Insurance Per Capita (Local Currency)',
    'hf2nec_ncu_pc': 'Social / Compulsory Insurance NEC Per Capita (Local Currency)',
    'hf3_ncu_pc': 'Voluntary Health Insurance Per Capita (Local Currency)',
    'hfnec_ncu_pc': 'Financing Agent NEC Per Capita (Local Currency)',
}

df_amr= df_amr.rename(columns=col_rename)

['location', 'code', 'region', 'income', 'year', 'che_gdp', 'che_pc_usd', 'che', 'gghed', 'pvtd', 'ext', 'dom_che', 'gghed_che', 'pvtd_che', 'oops_che', 'vpp_che', 'ext_che', 'gghed_gdp', 'gghed_gge', 'gghed_pc_usd', 'pvtd_pc_usd', 'oop_pc_usd', 'ext_pc_usd', 'tran_shi', 'shise_shi', 'cfa_che', 'gfa_che', 'chi_che', 'shi_che', 'chi_pvt_che', 'vfa_che', 'vhi_che', 'row_che', 'phc_usd_pc', 'phc_che', 'phc_gghed_usd_pc', 'gghed_phc_gghed', 'gghed_phc_phc', 'phc_ext_usd_pc', 'ext_phc_ext', 'ext_phc_phc', 'phc_public_gdp', 'phc_pvtd_usd_pc', 'pvtd_phc_pvtd', 'pvtd_phc_phc', 'hc62_che', 'hc62_g_gghed', 'hc62_ext_ext', 'fp3214_che', 'fp3214_gghed_fp3214', 'fp3214_ext_fp3214', 'dis1_che', 'dis11_che', 'dis12_che', 'dis13_che', 'dis16_che', 'dis2_che', 'dis21_che', 'dis22_che', 'dis23_che', 'dis3_che', 'dis4_che', 'dis5_che', 'disnec_che', 'dis1_g_gghed', 'dis11_g_gghed', 'dis12_g_gghed', 'dis13_g_gghed', 'dis16_g_gghed', 'dis2_g_gghed', 'dis21_g_gghed', 'dis22_g_gghed', 'dis23_g_gghed', 'dis3_g_gghed', 'dis4_g_gghed', 'dis5_g_gghed', 'disnec_g_gghed', 'dis1_ext_ext', 'dis11_ext_ext', 'dis12_ext_ext', 'dis13_ext_ext', 'dis16_ext_ext', 'dis2_ext_ext', 'dis21_ext_ext', 'dis22_ext_ext', 'dis23_ext_ext', 'dis3_ext_ext', 'dis4_ext_ext', 'dis5_ext_ext', 'disnec_ext_ext', 'hccov_che', 'hccov_usd_pc', 'hccov_gghed_gghed', 'hccov_ext_ext', 'gge_gdp', 'gdp_pc_usd', 'fs', 'fs1', 'fs11', 'fs12', 'fs13', 'fs14', 'fs2', 'fs3', 'fs31', 'fs32', 'fs33', 'fs34', 'fs4', 'fs5', 'fs6', 'fs61', 'fs62', 'fs63', 'fs6nec', 'fs7', 'fsnec', 'hf', 'hf1', 'hf11', 'hf12', 'hf121', 'hf122', 'hf12nec', 'hf13', 'hf1nec', 'hf2', 'hf21', 'hf22', 'hf23', 'hf2nec', 'hf3', 'hf4', 'hfnec', 'hc', 'hc1', 'hc11', 'hc12', 'hc13', 'hc131', 'hc132', 'hc133', 'hc139', 'hc13nec', 'hc14', 'hc1nec', 'hc2', 'hc21', 'hc22', 'hc23', 'hc24', 'hc2nec', 'hc3', 'hc31', 'hc32', 'hc33', 'hc34', 'hc3nec', 'hc4', 'hc41', 'hc42', 'hc43', 'hc4nec', 'hc5', 'hc51', 'hc511', 'hc512', 'hc513', 'hc52', 'hc5nec', 'hc6', 'hc61', 'hc62', 'fp3214', 'hc63', 'hc64', 'hc65', 'hc66', 'hc6nec', 'hc7', 'hc71', 'hc72', 'hc7nec', 'hc9', 'hc_gghed', 'hc1_gghed', 'hc11_gghed', 'hc12_gghed', 'hc13_gghed', 'hc131_gghed', 'hc132_gghed', 'hc133_gghed', 'hc139_gghed', 'hc13nec_gghed', 'hc14_gghed', 'hc1nec_gghed', 'hc2_gghed', 'hc21_gghed', 'hc22_gghed', 'hc23_gghed', 'hc24_gghed', 'hc3_gghed', 'hc31_gghed', 'hc32_gghed', 'hc33_gghed', 'hc34_gghed', 'hc3nec_gghed', 'hc4_gghed', 'hc41_gghed', 'hc42_gghed', 'hc43_gghed', 'hc5_gghed', 'hc51_gghed', 'hc511_gghed', 'hc512_gghed', 'hc513_gghed', 'hc52_gghed', 'hc5nec_gghed', 'hc6_gghed', 'hc61_gghed', 'hc62_gghed', 'fp3214_gghed', 'hc63_gghed', 'hc64_gghed', 'hc65_gghed', 'hc66_gghed', 'hc6nec_gghed', 'hc7_gghed', 'hc71_gghed', 'hc72_gghed', 'hc7nec_gghed', 'hc9_gghed', 'hc_ext', 'hc1_ext', 'hc11_ext', 'hc12_ext', 'hc13_ext', 'hc131_ext', 'hc132_ext', 'hc133_ext', 'hc139_ext', 'hc13nec_ext', 'hc14_ext', 'hc1nec_ext', 'hc2_ext', 'hc21_ext', 'hc22_ext', 'hc23_ext', 'hc24_ext', 'hc3_ext', 'hc31_ext', 'hc32_ext', 'hc33_ext', 'hc34_ext', 'hc3nec_ext', 'hc4_ext', 'hc41_ext', 'hc42_ext', 'hc43_ext', 'hc5_ext', 'hc51_ext', 'hc511_ext', 'hc512_ext', 'hc513_ext', 'hc52_ext', 'hc5nec_ext', 'hc6_ext', 'hc61_ext', 'hc62_ext', 'fp3214_ext', 'hc63_ext', 'hc64_ext', 'hc65_ext', 'hc66_ext', 'hc6nec_ext', 'hc7_ext', 'hc71_ext', 'hc72_ext', 'hc7nec_ext', 'hc9_ext', 'hc_pvtd', 'hc1_pvtd', 'hc11_pvtd', 'hc12_pvtd', 'hc13_pvtd', 'hc131_pvtd', 'hc132_pvtd', 'hc133_pvtd', 'hc139_pvtd', 'hc13nec_pvtd', 'hc14_pvtd', 'hc1nec_pvtd', 'hc2_pvtd', 'hc21_pvtd', 'hc22_pvtd', 'hc23_pvtd', 'hc24_pvtd', 'hc3_pvtd', 'hc31_pvtd', 'hc32_pvtd', 'hc33_pvtd', 'hc34_pvtd', 'hc3nec_pvtd', 'hc4_pvtd', 'hc41_pvtd', 'hc42_pvtd', 'hc43_pvtd', 'hc5_pvtd', 'hc51_pvtd', 'hc511_pvtd', 'hc512_pvtd', 'hc513_pvtd', 'hc52_pvtd', 'hc5nec_pvtd', 'hc6_pvtd', 'hc61_pvtd', 'hc62_pvtd', 'fp3214_pvtd', 'hc63_pvtd', 'hc64_pvtd', 'hc65_pvtd', 'hc66_pvtd', 'hc6nec_pvtd', 'hc7_pvtd', 'hc71_pvtd', 'hc72_pvtd', 'hc7nec_pvtd', 'hc9_pvtd', 'hcri1', 'dis', 'dis1', 'dis11', 'dis12', 'dis13', 'dis16', 'dis192', 'dis2', 'dis21', 'dis22', 'dis23', 'dis2nec', 'dis3', 'dis4', 'dis5', 'disnec', 'dis_gghed', 'dis1_gghed', 'dis11_gghed', 'dis12_gghed', 'dis13_gghed', 'dis16_gghed', 'dis192_gghed', 'dis2_gghed', 'dis21_gghed', 'dis22_gghed', 'dis23_gghed', 'dis2nec_gghed', 'dis3_gghed', 'dis4_gghed', 'dis5_gghed', 'disnec_gghed', 'dis_ext', 'dis1_ext', 'dis11_ext', 'dis12_ext', 'dis13_ext', 'dis16_ext', 'dis192_ext', 'dis2_ext', 'dis21_ext', 'dis22_ext', 'dis23_ext', 'dis2nec_ext', 'dis3_ext', 'dis4_ext', 'dis5_ext', 'disnec_ext', 'dis_pvtd', 'dis1_pvtd', 'dis11_pvtd', 'dis12_pvtd', 'dis13_pvtd', 'dis16_pvtd', 'dis192_pvtd', 'dis2_pvtd', 'dis21_pvtd', 'dis22_pvtd', 'dis23_pvtd', 'dis2nec_pvtd', 'dis3_pvtd', 'dis4_pvtd', 'dis5_pvtd', 'disnec_pvtd', 'hccov', 'hccov1', 'hccov2', 'hccov3', 'hccov4', 'hccov5', 'hccov_gghed', 'hccov_ext', 'hccov_pvtd', 'age1', 'age1_gghed', 'age1_ext', 'age1_pvtd', 'hp', 'hp1', 'hp11', 'hp12', 'hp13', 'hp1nec', 'hp2', 'hp21', 'hp22', 'hp29', 'hp3', 'hp31', 'hp32', 'hp33', 'hp34', 'hp35', 'hp3nec', 'hp4', 'hp41', 'hp42', 'hp49', 'hp5', 'hp51', 'hp52', 'hp59', 'hp6', 'hp7', 'hp71', 'hp72', 'hp73', 'hp79', 'hp8', 'hp81', 'hp82', 'hp83', 'hp9', 'hpnec', 'hk', 'hk1', 'hk11', 'hk111', 'hk112', 'hk113', 'hk_gghed', 'hk_ext', 'hk_pvtd', 'gdp', 'pfc', 'gge', 'ppp', 'xrt', 'gdpd', 'pop', 'che_usd', 'gghed_usd', 'pvtd_usd', 'ext_usd', 'fs_usd', 'fs1_usd', 'fs11_usd', 'fs12_usd', 'fs13_usd', 'fs14_usd', 'fs2_usd', 'fs3_usd', 'fs31_usd', 'fs32_usd', 'fs33_usd', 'fs34_usd', 'fs4_usd', 'fs5_usd', 'fs6_usd', 'fs61_usd', 'fs62_usd', 'fs63_usd', 'fs6nec_usd', 'fs7_usd', 'fsnec_usd', 'hf_usd', 'hf1_usd', 'hf11_usd', 'hf12_usd', 'hf121_usd', 'hf122_usd', 'hf12nec_usd', 'hf13_usd', 'hf1nec_usd', 'hf2_usd', 'hf21_usd', 'hf22_usd', 'hf23_usd', 'hf2nec_usd', 'hf3_usd', 'hf4_usd', 'hfnec_usd', 'hc_usd', 'hc1_usd', 'hc11_usd', 'hc12_usd', 'hc13_usd', 'hc131_usd', 'hc132_usd', 'hc133_usd', 'hc139_usd', 'hc13nec_usd', 'hc14_usd', 'hc1nec_usd', 'hc2_usd', 'hc21_usd', 'hc22_usd', 'hc23_usd', 'hc24_usd', 'hc2nec_usd', 'hc3_usd', 'hc31_usd', 'hc32_usd', 'hc33_usd', 'hc34_usd', 'hc3nec_usd', 'hc4_usd', 'hc41_usd', 'hc42_usd', 'hc43_usd', 'hc4nec_usd', 'hc5_usd', 'hc51_usd', 'hc511_usd', 'hc512_usd', 'hc513_usd', 'hc52_usd', 'hc5nec_usd', 'hc6_usd', 'hc61_usd', 'hc62_usd', 'fp3214_usd', 'hc63_usd', 'hc64_usd', 'hc65_usd', 'hc66_usd', 'hc6nec_usd', 'hc7_usd', 'hc71_usd', 'hc72_usd', 'hc7nec_usd', 'hc9_usd', 'hc_gghed_usd', 'hc1_gghed_usd', 'hc11_gghed_usd', 'hc12_gghed_usd', 'hc13_gghed_usd', 'hc131_gghed_usd', 'hc132_gghed_usd', 'hc133_gghed_usd', 'hc139_gghed_usd', 'hc13nec_gghed_usd', 'hc14_gghed_usd', 'hc1nec_gghed_usd', 'hc2_gghed_usd', 'hc21_gghed_usd', 'hc22_gghed_usd', 'hc23_gghed_usd', 'hc24_gghed_usd', 'hc3_gghed_usd', 'hc31_gghed_usd', 'hc32_gghed_usd', 'hc33_gghed_usd', 'hc34_gghed_usd', 'hc3nec_gghed_usd', 'hc4_gghed_usd', 'hc41_gghed_usd', 'hc42_gghed_usd', 'hc43_gghed_usd', 'hc5_gghed_usd', 'hc51_gghed_usd', 'hc511_gghed_usd', 'hc512_gghed_usd', 'hc513_gghed_usd', 'hc52_gghed_usd', 'hc5nec_gghed_usd', 'hc6_gghed_usd', 'hc61_gghed_usd', 'hc62_gghed_usd', 'fp3214_gghed_usd', 'hc63_gghed_usd', 'hc64_gghed_usd', 'hc65_gghed_usd', 'hc66_gghed_usd', 'hc6nec_gghed_usd', 'hc7_gghed_usd', 'hc71_gghed_usd', 'hc72_gghed_usd', 'hc7nec_gghed_usd', 'hc9_gghed_usd', 'hc_ext_usd', 'hc1_ext_usd', 'hc11_ext_usd', 'hc12_ext_usd', 'hc13_ext_usd', 'hc131_ext_usd', 'hc132_ext_usd', 'hc133_ext_usd', 'hc139_ext_usd', 'hc13nec_ext_usd', 'hc14_ext_usd', 'hc1nec_ext_usd', 'hc2_ext_usd', 'hc21_ext_usd', 'hc22_ext_usd', 'hc23_ext_usd', 'hc24_ext_usd', 'hc3_ext_usd', 'hc31_ext_usd', 'hc32_ext_usd', 'hc33_ext_usd', 'hc34_ext_usd', 'hc3nec_ext_usd', 'hc4_ext_usd', 'hc41_ext_usd', 'hc42_ext_usd', 'hc43_ext_usd', 'hc5_ext_usd', 'hc51_ext_usd', 'hc511_ext_usd', 'hc512_ext_usd', 'hc513_ext_usd', 'hc52_ext_usd', 'hc5nec_ext_usd', 'hc6_ext_usd', 'hc61_ext_usd', 'hc62_ext_usd', 'fp3214_ext_usd', 'hc63_ext_usd', 'hc64_ext_usd', 'hc65_ext_usd', 'hc66_ext_usd', 'hc6nec_ext_usd', 'hc7_ext_usd', 'hc71_ext_usd', 'hc72_ext_usd', 'hc7nec_ext_usd', 'hc9_ext_usd', 'hc_pvtd_usd', 'hc1_pvtd_usd', 'hc11_pvtd_usd', 'hc12_pvtd_usd', 'hc13_pvtd_usd', 'hc131_pvtd_usd', 'hc132_pvtd_usd', 'hc133_pvtd_usd', 'hc139_pvtd_usd', 'hc13nec_pvtd_usd', 'hc14_pvtd_usd', 'hc1nec_pvtd_usd', 'hc2_pvtd_usd', 'hc21_pvtd_usd', 'hc22_pvtd_usd', 'hc23_pvtd_usd', 'hc24_pvtd_usd', 'hc3_pvtd_usd', 'hc31_pvtd_usd', 'hc32_pvtd_usd', 'hc33_pvtd_usd', 'hc34_pvtd_usd', 'hc3nec_pvtd_usd', 'hc4_pvtd_usd', 'hc41_pvtd_usd', 'hc42_pvtd_usd', 'hc43_pvtd_usd', 'hc5_pvtd_usd', 'hc51_pvtd_usd', 'hc511_pvtd_usd', 'hc512_pvtd_usd', 'hc513_pvtd_usd', 'hc52_pvtd_usd', 'hc5nec_pvtd_usd', 'hc6_pvtd_usd', 'hc61_pvtd_usd', 'hc62_pvtd_usd', 'fp3214_pvtd_usd', 'hc63_pvtd_usd', 'hc64_pvtd_usd', 'hc65_pvtd_usd', 'hc66_pvtd_usd', 'hc6nec_pvtd_usd', 'hc7_pvtd_usd', 'hc71_pvtd_usd', 'hc72_pvtd_usd', 'hc7nec_pvtd_usd', 'hc9_pvtd_usd', 'hcri1_usd', 'dis_usd', 'dis1_usd', 'dis11_usd', 'dis12_usd', 'dis13_usd', 'dis16_usd', 'dis192_usd', 'dis2_usd', 'dis21_usd', 'dis22_usd', 'dis23_usd', 'dis2nec_usd', 'dis3_usd', 'dis4_usd', 'dis5_usd', 'disnec_usd', 'dis_gghed_usd', 'dis1_gghed_usd', 'dis11_gghed_usd', 'dis12_gghed_usd', 'dis13_gghed_usd', 'dis16_gghed_usd', 'dis192_gghed_usd', 'dis2_gghed_usd', 'dis21_gghed_usd', 'dis22_gghed_usd', 'dis23_gghed_usd', 'dis2nec_gghed_usd', 'dis3_gghed_usd', 'dis4_gghed_usd', 'dis5_gghed_usd', 'disnec_gghed_usd', 'dis_ext_usd', 'dis1_ext_usd', 'dis11_ext_usd', 'dis12_ext_usd', 'dis13_ext_usd', 'dis16_ext_usd', 'dis192_ext_usd', 'dis2_ext_usd', 'dis21_ext_usd', 'dis22_ext_usd', 'dis23_ext_usd', 'dis2nec_ext_usd', 'dis3_ext_usd', 'dis4_ext_usd', 'dis5_ext_usd', 'disnec_ext_usd', 'dis_pvtd_usd', 'dis1_pvtd_usd', 'dis11_pvtd_usd', 'dis12_pvtd_usd', 'dis13_pvtd_usd', 'dis16_pvtd_usd', 'dis192_pvtd_usd', 'dis2_pvtd_usd', 'dis21_pvtd_usd', 'dis22_pvtd_usd', 'dis23_pvtd_usd', 'dis2nec_pvtd_usd', 'dis3_pvtd_usd', 'dis4_pvtd_usd', 'dis5_pvtd_usd', 'disnec_pvtd_usd', 'hccov_usd', 'hccov1_usd', 'hccov2_usd', 'hccov3_usd', 'hccov4_usd', 'hccov5_usd', 'hccov_gghed_usd', 'hccov_ext_usd', 'hccov_pvtd_usd', 'age1_usd', 'age1_gghed_usd', 'age1_ext_usd', 'age1_pvtd_usd', 'hp_usd', 'hp1_usd', 'hp11_usd', 'hp12_usd', 'hp13_usd', 'hp1nec_usd', 'hp2_usd', 'hp21_usd', 'hp22_usd', 'hp29_usd', 'hp3_usd', 'hp31_usd', 'hp32_usd', 'hp33_usd', 'hp34_usd', 'hp35_usd', 'hp3nec_usd', 'hp4_usd', 'hp41_usd', 'hp42_usd', 'hp49_usd', 'hp5_usd', 'hp51_usd', 'hp52_usd', 'hp59_usd', 'hp6_usd', 'hp7_usd', 'hp71_usd', 'hp72_usd', 'hp73_usd', 'hp79_usd', 'hp8_usd', 'hp81_usd', 'hp82_usd', 'hp83_usd', 'hp9_usd', 'hpnec_usd', 'hk_usd', 'hk1_usd', 'hk11_usd', 'hk111_usd', 'hk112_usd', 'hk113_usd', 'hk_gghed_usd', 'hk_ext_usd', 'hk_pvtd_usd', 'gdp_usd', 'pfc_usd', 'gge_usd', 'che_ncu_pc', 'gghed_ncu_pc', 'pvtd_ncu_pc', 'ext_ncu_pc', 'fs_ncu_pc', 'fs1_ncu_pc', 'fs11_ncu_pc', 'fs12_ncu_pc', 'fs13_ncu_pc', 'fs14_ncu_pc', 'fs2_ncu_pc', 'fs3_ncu_pc', 'fs31_ncu_pc', 'fs32_ncu_pc', 'fs33_ncu_pc', 'fs34_ncu_pc', 'fs4_ncu_pc', 'fs5_ncu_pc', 'fs6_ncu_pc', 'fs61_ncu_pc', 'fs62_ncu_pc', 'fs63_ncu_pc', 'fs6nec_ncu_pc', 'fs7_ncu_pc', 'fsnec_ncu_pc', 'hf_ncu_pc', 'hf1_ncu_pc', 'hf11_ncu_pc', 'hf12_ncu_pc', 'hf121_ncu_pc', 'hf122_ncu_pc', 'hf12nec_ncu_pc', 'hf13_ncu_pc', 'hf1nec_ncu_pc', 'hf2_ncu_pc', 'hf21_ncu_pc', 'hf22_ncu_pc', 'hf23_ncu_pc', 'hf2nec_ncu_pc', 'hf3_ncu_pc', 'hf4_ncu_pc', 'hfnec_ncu_pc', 'hc_ncu_pc', 'hc1_ncu_pc', 'hc11_ncu_pc', 'hc12_ncu_pc', 'hc13_ncu_pc', 'hc131_ncu_pc', 'hc132_ncu_pc', 'hc133_ncu_pc', 'hc139_ncu_pc', 'hc13nec_ncu_pc', 'hc14_ncu_pc', 'hc1nec_ncu_pc', 'hc2_ncu_pc', 'hc21_ncu_pc', 'hc22_ncu_pc', 'hc23_ncu_pc', 'hc24_ncu_pc', 'hc2nec_ncu_pc', 'hc3_ncu_pc', 'hc31_ncu_pc', 'hc32_ncu_pc', 'hc33_ncu_pc', 'hc34_ncu_pc', 'hc3nec_ncu_pc', 'hc4_ncu_pc', 'hc41_ncu_pc', 'hc42_ncu_pc', 'hc43_ncu_pc', 'hc4nec_ncu_pc', 'hc5_ncu_pc', 'hc51_ncu_pc', 'hc511_ncu_pc', 'hc512_ncu_pc', 'hc513_ncu_pc', 'hc52_ncu_pc', 'hc5nec_ncu_pc', 'hc6_ncu_pc', 'hc61_ncu_pc', 'hc62_ncu_pc', 'fp3214_ncu_pc', 'hc63_ncu_pc', 'hc64_ncu_pc', 'hc65_ncu_pc', 'hc66_ncu_pc', 'hc6nec_ncu_pc', 'hc7_ncu_pc', 'hc71_ncu_pc', 'hc72_ncu_pc', 'hc7nec_ncu_pc', 'hc9_ncu_pc', 'hc_gghed_ncu_pc', 'hc1_gghed_ncu_pc', 'hc11_gghed_ncu_pc', 'hc12_gghed_ncu_pc', 'hc13_gghed_ncu_pc', 'hc131_gghed_ncu_pc', 'hc132_gghed_ncu_pc', 'hc133_gghed_ncu_pc', 'hc139_gghed_ncu_pc', 'hc13nec_gghed_ncu_pc', 'hc14_gghed_ncu_pc', 'hc1nec_gghed_ncu_pc', 'hc2_gghed_ncu_pc', 'hc21_gghed_ncu_pc', 'hc22_gghed_ncu_pc', 'hc23_gghed_ncu_pc', 'hc24_gghed_ncu_pc', 'hc3_gghed_ncu_pc', 'hc31_gghed_ncu_pc', 'hc32_gghed_ncu_pc', 'hc33_gghed_ncu_pc', 'hc34_gghed_ncu_pc', 'hc3nec_gghed_ncu_pc', 'hc4_gghed_ncu_pc', 'hc41_gghed_ncu_pc', 'hc42_gghed_ncu_pc', 'hc43_gghed_ncu_pc', 'hc5_gghed_ncu_pc', 'hc51_gghed_ncu_pc', 'hc511_gghed_ncu_pc', 'hc512_gghed_ncu_pc', 'hc513_gghed_ncu_pc', 'hc52_gghed_ncu_pc', 'hc5nec_gghed_ncu_pc', 'hc6_gghed_ncu_pc', 'hc61_gghed_ncu_pc', 'hc62_gghed_ncu_pc', 'fp3214_gghed_ncu_pc', 'hc63_gghed_ncu_pc', 'hc64_gghed_ncu_pc', 'hc65_gghed_ncu_pc', 'hc66_gghed_ncu_pc', 'hc6nec_gghed_ncu_pc', 'hc7_gghed_ncu_pc', 'hc71_gghed_ncu_pc', 'hc72_gghed_ncu_pc', 'hc7nec_gghed_ncu_pc', 'hc9_gghed_ncu_pc', 'hc_ext_ncu_pc', 'hc1_ext_ncu_pc', 'hc11_ext_ncu_pc', 'hc12_ext_ncu_pc', 'hc13_ext_ncu_pc', 'hc131_ext_ncu_pc', 'hc132_ext_ncu_pc', 'hc133_ext_ncu_pc', 'hc139_ext_ncu_pc', 'hc13nec_ext_ncu_pc', 'hc14_ext_ncu_pc', 'hc1nec_ext_ncu_pc', 'hc2_ext_ncu_pc', 'hc21_ext_ncu_pc', 'hc22_ext_ncu_pc', 'hc23_ext_ncu_pc', 'hc24_ext_ncu_pc', 'hc3_ext_ncu_pc', 'hc31_ext_ncu_pc', 'hc32_ext_ncu_pc', 'hc33_ext_ncu_pc', 'hc34_ext_ncu_pc', 'hc3nec_ext_ncu_pc', 'hc4_ext_ncu_pc', 'hc41_ext_ncu_pc', 'hc42_ext_ncu_pc', 'hc43_ext_ncu_pc', 'hc5_ext_ncu_pc', 'hc51_ext_ncu_pc', 'hc511_ext_ncu_pc', 'hc512_ext_ncu_pc', 'hc513_ext_ncu_pc', 'hc52_ext_ncu_pc', 'hc5nec_ext_ncu_pc', 'hc6_ext_ncu_pc', 'hc61_ext_ncu_pc', 'hc62_ext_ncu_pc', 'fp3214_ext_ncu_pc']

In [20]:
df_amr

,location,code,region,income,year,Health Expenditure % of GDP,Health Expenditure Per Capita (USD),Current Health Expenditure (Local Currency),Govt Health Expenditure (Local Currency),Private Health Expenditure (Local Currency),...,State Health Authority NEC Per Capita (Local Currency),Local Govt Health Authority Per Capita (Local Currency),Other Public Health Authority NEC Per Capita (Local Currency),Social Health Insurance Funds Per Capita (Local Currency),Social Health Insurance OECD-Type Per Capita (Local Currency),Other Social Health Insurance Per Capita (Local Currency),Compulsory Private Insurance Per Capita (Local Currency),Social / Compulsory Insurance NEC Per Capita (Local Currency),Voluntary Health Insurance Per Capita (Local Currency),Financing Agent NEC Per Capita (Local Currency)
1101,Antigua and Barbuda,ATG,AMR,High,2000,4.3,520,105,61,44,...,0.0,0.0,NaN,275,275,0,NaN,0.0,312,0
1102,Antigua and Barbuda,ATG,AMR,High,2001,5.0,572,118,69,48,...,0.0,0.0,NaN,280,280,0,NaN,0.0,351,0
1103,Antigua and Barbuda,ATG,AMR,High,2002,4.8,559,116,68,48,...,0.0,0.0,NaN,282,282,0,NaN,0.0,343,0
1104,Antigua and Barbuda,ATG,AMR,High,2003,5.0,614,129,77,52,...,0.0,0.0,NaN,280,280,0,NaN,0.0,385,0
1105,Antigua and Barbuda,ATG,AMR,High,2004,4.6,598,127,74,53,...,0.0,0.0,NaN,285,284,1,NaN,0.0,392,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1921,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2019,2.2,113,9,3,6,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
1922,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2020,4.1,153,245,91,154,...,0.0,0.0,0.0,3,3,0,0,0.0,2,0
1923,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2021,4.1,162,"3,219","1,079","2,125",...,0.0,0.0,0.0,44,43,1,0,0.0,32,0
1924,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2022,4.6,209,"12,185","5,530","6,569",...,0.0,0.0,0.0,128,125,3,0,0.0,107,0
1925,Venezuela (Bolivarian Republic of),VEN,AMR,Upper-middle,2023,3.8,186,"45,674","14,493","30,936",...,0.0,0.0,0.0,623,613,9,0,0.0,479,0