In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("NHE2024.csv", encoding='latin1', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
0,NATIONAL HEALTH EXPENDITURES BY TYPE OF SERVIC...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Expenditure Amount (Millions),1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
2,Total National Health Expenditures,"27,122","29,060","31,765","34,558","38,245","41,627","45,752","51,186","58,015",...,"3,177,216","3,324,095","3,464,208","3,637,678","3,805,121","4,204,311","4,376,932","4,586,625","4,925,324","5,278,588"
3,Out of pocket,"12,778","13,193","14,085","15,171","16,669","17,863","18,132","17,985","19,951",...,"360,681","375,394","385,333","403,033","420,412","412,276","457,160","491,924","525,424","556,554"
4,Health Insurance,"7,324","8,043","8,785","9,660","10,710","11,722","15,357","20,789","24,010",...,"2,293,717","2,403,044","2,497,226","2,627,731","2,744,967","2,847,640","3,062,007","3,292,037","3,614,341","3,892,868"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,State and Local Gov't,54,55,63,79,87,98,130,149,159,...,"10,937","11,696","12,294","13,365","13,977","15,207","16,637","17,688","18,220","19,671"
541,"* Other Federal Programs include OEO, Federal ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
542,** Other State and Local Programs include Stat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
543,NOTE: Numbers may not add to totals due to rou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
544,SOURCE: Centers for Medicare & Medicaid Servi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
years = df.iloc[1, 1:].tolist()
df.columns = ['Category'] + years
df = df.drop(index=[0, 1]).reset_index(drop=True)

In [4]:
df

,Category,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Total National Health Expenditures,"27,122","29,060","31,765","34,558","38,245","41,627","45,752","51,186","58,015",...,"3,177,216","3,324,095","3,464,208","3,637,678","3,805,121","4,204,311","4,376,932","4,586,625","4,925,324","5,278,588"
1,Out of pocket,"12,778","13,193","14,085","15,171","16,669","17,863","18,132","17,985","19,951",...,"360,681","375,394","385,333","403,033","420,412","412,276","457,160","491,924","525,424","556,554"
2,Health Insurance,"7,324","8,043","8,785","9,660","10,710","11,722","15,357","20,789","24,010",...,"2,293,717","2,403,044","2,497,226","2,627,731","2,744,967","2,847,640","3,062,007","3,292,037","3,614,341","3,892,868"
3,Private Health Insurance,"5,639","6,275","6,963","7,720","8,791","9,772","9,980","10,132","11,462",...,"981,936","1,037,028","1,081,394","1,142,822","1,179,333","1,184,273","1,263,112","1,358,610","1,511,174","1,644,592"
4,Medicare,-,-,-,-,-,-,"1,842","4,924","6,218",...,"647,728","675,730","704,948","751,592","805,227","833,827","894,587","951,731","1,037,275","1,118,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,State and Local Gov't,54,55,63,79,87,98,130,149,159,...,"10,937","11,696","12,294","13,365","13,977","15,207","16,637","17,688","18,220","19,671"
539,"* Other Federal Programs include OEO, Federal ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,** Other State and Local Programs include Stat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,NOTE: Numbers may not add to totals due to rou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
542,SOURCE: Centers for Medicare & Medicaid Servi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Transpose dataset**

In [5]:
df = df.set_index('Category').T.reset_index()
df = df.rename(columns={'index': 'Year'})

**rename rows into their years**

In [6]:
df

Category,Year,Total National Health Expenditures,Out of pocket,Health Insurance,Private Health Insurance,Medicare,Medicaid (Title XIX),Federal,State and Local,CHIP (Title XIX and Title XXI),...,Federal Gov't,State and Local Gov't,Equipment,Private,Federal Gov't,State and Local Gov't,"* Other Federal Programs include OEO, Federal General and Medical, Federal General and Medical NEC, and High Risk Pools under ACA",** Other State and Local Programs include State and Local Subsidies and TDI,"NOTE: Numbers may not add to totals due to rounding. Dollar amounts shown are in current dollars. """" Not applicable; Medicare and Medicaid became effective July 1966. The Children's Health Insurance Program became effective in 1998.","SOURCE: Centers for Medicare & Medicaid Services, Office of the Actuary, National Health Statistics Group."
0,1960,"27,122","12,778","7,324","5,639",-,-,-,-,-,...,123,347,335,278,3,54,NaN,NaN,NaN,NaN
1,1961,"29,060","13,193","8,043","6,275",-,-,-,-,-,...,130,316,377,316,6,55,NaN,NaN,NaN,NaN
2,1962,"31,765","14,085","8,785","6,963",-,-,-,-,-,...,134,345,442,377,2,63,NaN,NaN,NaN,NaN
3,1963,"34,558","15,171","9,660","7,720",-,-,-,-,-,...,157,337,535,455,1,79,NaN,NaN,NaN,NaN
4,1964,"38,245","16,669","10,710","8,791",-,-,-,-,-,...,166,367,558,468,3,87,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2020,"4,204,311","412,276","2,847,640","1,184,273","833,827","672,504","460,639","211,865","21,208",...,"2,021","6,967","77,977","41,497","21,274","15,207",NaN,NaN,NaN,NaN
61,2021,"4,376,932","457,160","3,062,007","1,263,112","894,587","738,064","515,555","222,509","22,451",...,"2,039","7,447","87,851","45,481","25,733","16,637",NaN,NaN,NaN,NaN
62,2022,"4,586,625","491,924","3,292,037","1,358,610","951,731","809,899","572,149","237,750","23,743",...,"2,539","7,980","94,568","45,533","31,348","17,688",NaN,NaN,NaN,NaN
63,2023,"4,925,324","525,424","3,614,341","1,511,174","1,037,275","873,681","592,568","281,112","24,617",...,"3,195","9,044","93,535","45,980","29,334","18,220",NaN,NaN,NaN,NaN
64,2024,"5,278,588","556,554","3,892,868","1,644,592","1,118,000","931,692","596,694","334,998","30,995",...,"3,388","9,891","97,144","47,475","29,998","19,671",NaN,NaN,NaN,NaN

In [7]:
df.columns

Index(['Year', 'Total National Health Expenditures', '     Out of pocket',
       '     Health Insurance', '          Private Health Insurance',
       '          Medicare', '          Medicaid (Title XIX)',
       '                          Federal  ',
       '                          State and Local',
       '          CHIP (Title XIX and Title XXI)',
       ...
       '         Federal Gov't', '         State and Local Gov't',
       '     Equipment', '          Private ', '          Federal Gov't',
       '          State and Local Gov't',
       '* Other Federal Programs include OEO, Federal General and Medical, Federal General and Medical NEC, and High Risk Pools under ACA',
       '** Other State and Local Programs include State and Local Subsidies and TDI',
       'NOTE: Numbers may not add to totals due to rounding. Dollar amounts shown are in current dollars.   "" Not applicable; Medicare and Medicaid became effective July 1966.  The Children's Health Insurance Program became effective in 1998.',
       'SOURCE:  Centers for Medicare & Medicaid Services, Office of the Actuary, National Health Statistics Group.'],
      dtype='object', name='Category', length=544)

**Total health expenditures seems like the target variable**

In [8]:
(df.isna().sum() / len(df)).sort_values(ascending=False) * 100

Category
SOURCE:  Centers for Medicare & Medicaid Services, Office of the Actuary, National Health Statistics Group.    100.0
         Other State and Local Programs**                                                                      100.0
     Out of pocket                                                                                             100.0
         Worksite Health Care                                                                                  100.0
         Other Private Revenues                                                                                100.0
                                                                                                               ...
         Worksite Health Care                                                                                    0.0
     Other Third Party Payers and Programs                                                                       0.0
         Department of Veterans Affairs                                                                          0.0
         Department of Defense                                                                                   0.0
                          State and Local                                                                        0.0
Length: 544, dtype: float64

In [9]:
df = df.iloc[:, :-4]

In [10]:
df

Category,Year,Total National Health Expenditures,Out of pocket,Health Insurance,Private Health Insurance,Medicare,Medicaid (Title XIX),Federal,State and Local,CHIP (Title XIX and Title XXI),...,Federal Gov't,State and Local Gov't,Structures,Private,Federal Gov't,State and Local Gov't,Equipment,Private,Federal Gov't,State and Local Gov't
0,1960,"27,122","12,778","7,324","5,639",-,-,-,-,-,...,126,401,"1,539","1,069",123,347,335,278,3,54
1,1961,"29,060","13,193","8,043","6,275",-,-,-,-,-,...,136,371,"1,611","1,165",130,316,377,316,6,55
2,1962,"31,765","14,085","8,785","6,963",-,-,-,-,-,...,136,408,"1,992","1,513",134,345,442,377,2,63
3,1963,"34,558","15,171","9,660","7,720",-,-,-,-,-,...,158,416,"2,003","1,509",157,337,535,455,1,79
4,1964,"38,245","16,669","10,710","8,791",-,-,-,-,-,...,169,454,"2,423","1,890",166,367,558,468,3,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2020,"4,204,311","412,276","2,847,640","1,184,273","833,827","672,504","460,639","211,865","21,208",...,"23,295","22,174","61,721","52,733","2,021","6,967","77,977","41,497","21,274","15,207"
61,2021,"4,376,932","457,160","3,062,007","1,263,112","894,587","738,064","515,555","222,509","22,451",...,"27,772","24,084","68,106","58,620","2,039","7,447","87,851","45,481","25,733","16,637"
62,2022,"4,586,625","491,924","3,292,037","1,358,610","951,731","809,899","572,149","237,750","23,743",...,"33,887","25,668","64,016","53,497","2,539","7,980","94,568","45,533","31,348","17,688"
63,2023,"4,925,324","525,424","3,614,341","1,511,174","1,037,275","873,681","592,568","281,112","24,617",...,"32,529","27,264","68,426","56,187","3,195","9,044","93,535","45,980","29,334","18,220"
64,2024,"5,278,588","556,554","3,892,868","1,644,592","1,118,000","931,692","596,694","334,998","30,995",...,"33,386","29,562","71,091","57,812","3,388","9,891","97,144","47,475","29,998","19,671"

In [11]:
df = df.iloc[6:]
df

Category,Year,Total National Health Expenditures,Out of pocket,Health Insurance,Private Health Insurance,Medicare,Medicaid (Title XIX),Federal,State and Local,CHIP (Title XIX and Title XXI),...,Federal Gov't,State and Local Gov't,Structures,Private,Federal Gov't,State and Local Gov't,Equipment,Private,Federal Gov't,State and Local Gov't
6,1966,"45,752","18,132","15,357","9,980","1,842","1,304",632,672,-,...,188,530,"2,670","2,083",187,400,672,541,1,130
7,1967,"51,186","17,985","20,789","10,132","4,924","3,141","1,525","1,616",-,...,157,736,"2,676","1,950",139,587,767,600,18,149
8,1968,"58,015","19,951","24,010","11,462","6,218","3,541","1,835","1,707",-,...,166,837,"3,129","2,311",140,678,851,666,26,159
9,1969,"65,417","21,911","27,191","12,988","7,045","4,174","2,298","1,877",-,...,209,955,"4,082","3,184",128,770,976,710,81,185
10,1970,"74,077","24,208","31,342","15,078","7,672","5,290","2,842","2,447",-,...,324,999,"4,680","3,739",159,782,"1,111",729,165,217
11,1971,"82,380","25,515","36,205","17,318","8,443","6,695","3,810","2,886",-,...,294,"1,376","5,604","4,252",211,"1,141","1,100",782,83,235
12,1972,"92,385","27,805","41,954","20,027","9,325","8,314","4,547","3,766",-,...,515,"1,358","6,047","4,741",205,"1,101","1,456",889,310,257
13,1973,"102,654","30,737","47,296","22,263","10,730","9,423","4,933","4,490",-,...,718,"1,391","6,024","4,727",209,"1,088","1,901","1,089",509,303
14,1974,"116,313","33,295","55,214","25,338","13,428","11,073","6,277","4,797",-,...,744,"1,794","6,488","4,816",253,"1,419","2,207","1,341",491,375
15,1975,"132,656","36,031","65,476","29,723","16,336","13,446","7,409","6,037",-,...,965,"1,917","6,689","4,842",364,"1,483","2,656","1,621",601,434
16,1976,"152,022","39,278","77,952","36,309","19,694","15,188","9,153","6,036",-,...,"1,042","2,178","7,252","5,138",415,"1,699","3,073","1,967",627,479
17,1977,"172,642","43,133","91,591","44,168","22,891","17,464","9,896","7,568",-,...,987,"2,094","7,052","5,007",489,"1,556","3,462","2,426",498,538
18,1978,"193,947","46,035","104,750","50,691","26,668","19,465","10,919","8,547",-,...,"1,245","2,169","7,193","5,103",576,"1,514","4,272","2,948",669,655
19,1979,"219,655","49,915","120,692","58,907","30,922","22,332","12,705","9,627",-,...,"1,145","2,507","7,652","5,399",558,"1,695","5,034","3,635",587,812
20,1980,"253,217","55,251","140,203","67,095","37,387","26,032","14,521","11,511",-,...,"1,497","2,911","8,831","6,227",648,"1,956","6,296","4,492",849,955
21,1981,"293,578","61,935","165,159","79,233","44,769","30,307","16,902","13,405",-,...,"1,748","2,972","10,218","7,598",753,"1,867","7,571","5,471",995,"1,105"
22,1982,"330,940","68,608","187,551","91,127","52,351","32,011","17,843","14,168",-,...,"1,689","3,231","11,782","9,168",700,"1,914","8,893","6,587",989,"1,317"
23,1983,"364,789","74,653","209,156","101,543","59,559","35,266","19,587","15,679",-,...,"2,225","3,221","12,696","10,295",673,"1,728","10,053","7,008","1,552","1,493"
24,1984,"401,880","82,410","232,952","114,600","66,207","38,233","21,096","17,137",-,...,"2,622","3,455","12,431","9,937",784,"1,710","10,889","7,306","1,838","1,745"
25,1985,"439,871","91,564","254,558","126,596","71,829","40,937","22,594","18,343",-,...,"2,792","3,760","11,406","8,869",780,"1,757","11,418","7,403","2,012","2,003"
26,1986,"472,263","99,649","270,200","131,578","76,829","45,383","25,187","20,196",-,...,"3,216","3,989","11,322","8,589",874,"1,859","11,981","7,509","2,342","2,130"
27,1987,"514,458","105,838","295,374","144,516","83,081","50,339","27,868","22,471",-,...,"3,566","4,371","12,722","9,690",997,"2,035","12,923","8,018","2,569","2,336"
28,1988,"576,651","116,237","332,523","170,070","88,965","55,080","30,995","24,085",-,...,"3,394","4,644","14,608","11,641",918,"2,049","14,434","9,363","2,476","2,595"
29,1989,"642,135","122,585","380,344","197,849","101,137","61,952","35,077","26,876",-,...,"3,639","5,254","15,158","12,165",861,"2,132","16,829","10,929","2,778","3,122"
30,1990,"718,689","133,752","431,117","225,890","110,182","73,661","42,607","31,054",-,...,"3,689","5,766","17,250","13,831",976,"2,443","18,627","12,591","2,713","3,323"
31,1991,"785,935","136,761","484,012","246,943","120,469","93,211","56,847","36,364",-,...,"4,312","6,050","17,000","13,448",864,"2,688","21,228","14,418","3,448","3,362"
32,1992,"852,198","139,127","534,417","266,111","135,905","108,186","68,602","39,585",-,...,"4,327","6,505","18,605","14,619",938,"3,048","23,407","16,561","3,389","3,457"
33,1993,"914,869","140,230","583,418","285,435","149,965","122,373","76,961","45,412",-,...,"4,892","6,873","20,143","15,898","1,066","3,179","24,268","16,748","3,826","3,694"
34,1994,"965,586","138,447","626,340","297,811","167,670","134,414","81,052","53,363",-,...,"4,975","6,580","21,086","17,094","1,025","2,967","24,762","17,199","3,950","3,613"
35,1995,"1,019,953","141,957","669,643","313,502","184,393","144,862","85,945","58,917",-,...,"5,272","6,740","21,141","16,939","1,125","3,077","25,756","17,946","4,147","3,663"
36,1996,"1,073,087","148,260","708,948","330,510","198,750","152,170","91,099","61,071",-,...,"5,883","6,782","21,894","17,517","1,334","3,043","27,385","19,097","4,549","3,739"
37,1997,"1,132,396","158,675","744,890","346,123","210,376","160,849","94,954","65,896",-,...,"5,289","7,417","23,205","18,632","1,346","3,227","28,809","20,676","3,943","4,190"
38,1998,"1,197,785","173,880","775,102","367,736","209,420","169,013","98,649","70,364",399,...,"7,587","7,835","23,865","19,597","1,018","3,250","33,167","22,013","6,569","4,585"
39,1999,"1,272,521","184,280","825,840","397,315","213,173","183,466","107,151","76,315","1,723",...,"8,209","7,870","25,483","21,611",852,"3,020","35,558","23,351","7,357","4,850"
40,2000,"1,365,184","197,580","897,114","436,114","224,829","200,367","116,838","83,529","3,012",...,"7,611","8,014","25,239","21,561",774,"2,904","34,939","22,992","6,837","5,110"
41,2001,"1,482,478","205,825","990,298","477,802","247,686","224,136","132,216","91,920","4,169",...,"7,786","8,518","26,117","22,054",723,"3,340","35,353","23,112","7,063","5,178"
42,2002,"1,630,533","219,435","1,097,569","537,035","265,381","248,022","145,208","102,813","5,494",...,"9,376","9,148","29,230","24,336",873,"4,021","40,207","26,577","8,503","5,127"
43,2003,"1,770,023","235,460","1,195,341","588,671","282,668","268,965","160,795","108,170","6,296",...,"9,674","9,823","31,009","26,034",711,"4,264","42,703","28,181","8,963","5,559"
44,2004,"1,894,161","248,765","1,287,127","625,246","311,122","290,743","172,317","118,426","7,167",...,"10,014","10,531","32,992","27,945",659,"4,388","45,360","29,861","9,355","6,143"
45,2005,"2,026,262","264,965","1,383,057","670,080","339,762","309,351","177,514","131,838","7,566",...,"10,401","11,669","36,041","30,436",681,"4,924","49,171","32,707","9,720","6,745"
46,2006,"2,163,806","278,349","1,484,752","704,389","403,692","306,680","173,945","132,736","8,366",...,"11,709","13,111","41,651","35,244",746,"5,661","50,185","31,772","10,963","7,450"
47,2007,"2,304,160","294,246","1,580,302","747,114","432,749","325,856","185,559","140,296","9,123",...,"12,245","14,921","47,344","39,769","1,014","6,561","56,292","36,701","11,231","8,360"
48,2008,"2,400,950","301,151","1,661,038","767,744","466,969","344,397","203,209","141,188","10,211",...,"13,533","16,138","52,470","44,559",944,"6,967","59,521","37,762","12,589","9,171"
49,2009,"2,491,503","298,232","1,755,973","792,399","498,627","374,709","247,532","127,177","11,106",...,"14,507","15,554","47,595","39,008","1,763","6,824","54,257","32,783","12,744","8,730"
50,2010,"2,588,734","303,421","1,830,207","817,682","519,534","397,425","266,497","130,929","11,540",...,"16,306","15,221","46,788","38,107","2,127","6,554","56,214","33,368","14,179","8,667"
51,2011,"2,676,377","312,304","1,900,677","849,185","544,564","406,797","247,309","159,488","11,988",...,"16,909","16,060","48,076","38,524","2,589","6,963","61,098","37,681","14,320","9,097"
52,2012,"2,784,281","325,074","1,971,573","878,105","568,309","422,783","243,302","179,481","12,615",...,"17,378","16,407","50,168","40,521","2,620","7,027","64,613","40,475","14,758","9,380"
53,2013,"2,859,107","333,801","2,019,966","880,207","588,855","444,981","256,690","188,291","13,497",...,"15,881","17,084","51,407","41,486","2,660","7,261","64,994","41,950","13,221","9,823"
54,2014,"3,010,322","345,400","2,154,894","926,763","617,326","498,214","305,960","192,254","13,212",...,"17,013","16,787","50,420","41,645","2,348","6,427","63,447","38,422","14,665","10,360"
55,2015,"3,177,216","360,681","2,293,717","981,936","647,728","542,995","342,770","200,226","14,748",...,"17,414","16,793","50,549","42,451","2,242","5,856","67,946","41,837","15,172","10,937"
56,2016,"3,324,095","375,394","2,403,044","1,037,028","675,730","564,869","357,834","207,035","16,778",...,"18,292","17,633","50,654","42,577","2,140","5,937","70,770","42,922","16,152","11,696"
57,2017,"3,464,208","385,333","2,497,226","1,081,394","704,948","578,795","361,594","217,201","18,079",...,"18,432","18,468","58,281","50,016","2,091","6,174","74,096","45,461","16,341","12,294"
58,2018,"3,637,678","403,033","2,627,731","1,142,822","751,592","596,795","372,494","224,301","18,620",...,"20,501","19,620","61,940","53,469","2,216","6,255","77,023","45,372","18,285","13,365"
59,2019,"3,805,121","420,412","2,744,967","1,179,333","805,227","615,388","387,945","227,443","19,927",...,"21,511","20,294","64,279","55,848","2,114","6,317","77,510","44,136","19,397","13,977"
60,2020,"4,204,311","412,276","2,847,640","1,184,273","833,827","672,504","460,639","211,865","21,208",...,"23,295","22,174","61,721","52,733","2,021","6,967","77,977","41,497","21,274","15,207"
61,2021,"4,376,932","457,160","3,062,007","1,263,112","894,587","738,064","515,555","222,509","22,451",...,"27,772","24,084","68,106","58,620","2,039","7,447","87,851","45,481","25,733","16,637"
62,2022,"4,586,625","491,924","3,292,037","1,358,610","951,731","809,899","572,149","237,750","23,743",...,"33,887","25,668","64,016","53,497","2,539","7,980","94,568","45,533","31,348","17,688"
63,2023,"4,925,324","525,424","3,614,341","1,511,174","1,037,275","873,681","592,568","281,112","24,617",...,"32,529","27,264","68,426","56,187","3,195","9,044","93,535","45,980","29,334","18,220"
64,2024,"5,278,588","556,554","3,892,868","1,644,592","1,118,000","931,692","596,694","334,998","30,995",...,"33,386","29,562","71,091","57,812","3,388","9,891","97,144","47,475","29,998","19,671"

In [12]:
df = df.drop(df.columns[9:12], axis=1)
df

Category,Year,Total National Health Expenditures,Out of pocket,Health Insurance,Private Health Insurance,Medicare,Medicaid (Title XIX),Department of Defense,Department of Veterans Affairs,Other Third Party Payers and Programs,...,Federal Gov't,State and Local Gov't,Structures,Private,Federal Gov't,State and Local Gov't,Equipment,Private,Federal Gov't,State and Local Gov't
6,1966,"45,752","18,132","15,357","9,980","1,842","1,304","1,078","1,153","6,563",...,188,530,"2,670","2,083",187,400,672,541,1,130
7,1967,"51,186","17,985","20,789","10,132","4,924","3,141","1,324","1,268","6,333",...,157,736,"2,676","1,950",139,587,767,600,18,149
8,1968,"58,015","19,951","24,010","11,462","6,218","3,541","1,445","1,344","7,227",...,166,837,"3,129","2,311",140,678,851,666,26,159
9,1969,"65,417","21,911","27,191","12,988","7,045","4,174","1,499","1,484","8,158",...,209,955,"4,082","3,184",128,770,976,710,81,185
10,1970,"74,077","24,208","31,342","15,078","7,672","5,290","1,582","1,719","9,427",...,324,999,"4,680","3,739",159,782,"1,111",729,165,217
11,1971,"82,380","25,515","36,205","17,318","8,443","6,695","1,766","1,983","10,171",...,294,"1,376","5,604","4,252",211,"1,141","1,100",782,83,235
12,1972,"92,385","27,805","41,954","20,027","9,325","8,314","1,997","2,291","10,911",...,515,"1,358","6,047","4,741",205,"1,101","1,456",889,310,257
13,1973,"102,654","30,737","47,296","22,263","10,730","9,423","2,235","2,646","12,071",...,718,"1,391","6,024","4,727",209,"1,088","1,901","1,089",509,303
14,1974,"116,313","33,295","55,214","25,338","13,428","11,073","2,475","2,900","13,759",...,744,"1,794","6,488","4,816",253,"1,419","2,207","1,341",491,375
15,1975,"132,656","36,031","65,476","29,723","16,336","13,446","2,590","3,381","15,466",...,965,"1,917","6,689","4,842",364,"1,483","2,656","1,621",601,434
16,1976,"152,022","39,278","77,952","36,309","19,694","15,188","2,695","4,066","17,545",...,"1,042","2,178","7,252","5,138",415,"1,699","3,073","1,967",627,479
17,1977,"172,642","43,133","91,591","44,168","22,891","17,464","2,922","4,146","19,726",...,987,"2,094","7,052","5,007",489,"1,556","3,462","2,426",498,538
18,1978,"193,947","46,035","104,750","50,691","26,668","19,465","3,067","4,859","22,671",...,"1,245","2,169","7,193","5,103",576,"1,514","4,272","2,948",669,655
19,1979,"219,655","49,915","120,692","58,907","30,922","22,332","3,457","5,073","26,183",...,"1,145","2,507","7,652","5,399",558,"1,695","5,034","3,635",587,812
20,1980,"253,217","55,251","140,203","67,095","37,387","26,032","3,949","5,740","30,762",...,"1,497","2,911","8,831","6,227",648,"1,956","6,296","4,492",849,955
21,1981,"293,578","61,935","165,159","79,233","44,769","30,307","4,588","6,261","35,459",...,"1,748","2,972","10,218","7,598",753,"1,867","7,571","5,471",995,"1,105"
22,1982,"330,940","68,608","187,551","91,127","52,351","32,011","5,158","6,905","39,459",...,"1,689","3,231","11,782","9,168",700,"1,914","8,893","6,587",989,"1,317"
23,1983,"364,789","74,653","209,156","101,543","59,559","35,266","5,393","7,396","42,437",...,"2,225","3,221","12,696","10,295",673,"1,728","10,053","7,008","1,552","1,493"
24,1984,"401,880","82,410","232,952","114,600","66,207","38,233","5,842","8,070","45,748",...,"2,622","3,455","12,431","9,937",784,"1,710","10,889","7,306","1,838","1,745"
25,1985,"439,871","91,564","254,558","126,596","71,829","40,937","6,864","8,332","51,393",...,"2,792","3,760","11,406","8,869",780,"1,757","11,418","7,403","2,012","2,003"
26,1986,"472,263","99,649","270,200","131,578","76,829","45,383","7,634","8,775","57,722",...,"3,216","3,989","11,322","8,589",874,"1,859","11,981","7,509","2,342","2,130"
27,1987,"514,458","105,838","295,374","144,516","83,081","50,339","8,202","9,236","64,004",...,"3,566","4,371","12,722","9,690",997,"2,035","12,923","8,018","2,569","2,336"
28,1988,"576,651","116,237","332,523","170,070","88,965","55,080","8,778","9,629","72,745",...,"3,394","4,644","14,608","11,641",918,"2,049","14,434","9,363","2,476","2,595"
29,1989,"642,135","122,585","380,344","197,849","101,137","61,952","9,272","10,134","77,708",...,"3,639","5,254","15,158","12,165",861,"2,132","16,829","10,929","2,778","3,122"
30,1990,"718,689","133,752","431,117","225,890","110,182","73,661","10,446","10,939","85,267",...,"3,689","5,766","17,250","13,831",976,"2,443","18,627","12,591","2,713","3,323"
31,1991,"785,935","136,761","484,012","246,943","120,469","93,211","11,536","11,852","90,986",...,"4,312","6,050","17,000","13,448",864,"2,688","21,228","14,418","3,448","3,362"
32,1992,"852,198","139,127","534,417","266,111","135,905","108,186","11,621","12,594","97,176",...,"4,327","6,505","18,605","14,619",938,"3,048","23,407","16,561","3,389","3,457"
33,1993,"914,869","140,230","583,418","285,435","149,965","122,373","12,025","13,621","103,558",...,"4,892","6,873","20,143","15,898","1,066","3,179","24,268","16,748","3,826","3,694"
34,1994,"965,586","138,447","626,340","297,811","167,670","134,414","11,833","14,612","107,598",...,"4,975","6,580","21,086","17,094","1,025","2,967","24,762","17,199","3,950","3,613"
35,1995,"1,019,953","141,957","669,643","313,502","184,393","144,862","12,045","14,840","111,784",...,"5,272","6,740","21,141","16,939","1,125","3,077","25,756","17,946","4,147","3,663"
36,1996,"1,073,087","148,260","708,948","330,510","198,750","152,170","11,951","15,567","116,415",...,"5,883","6,782","21,894","17,517","1,334","3,043","27,385","19,097","4,549","3,739"
37,1997,"1,132,396","158,675","744,890","346,123","210,376","160,849","12,053","15,488","122,346",...,"5,289","7,417","23,205","18,632","1,346","3,227","28,809","20,676","3,943","4,190"
38,1998,"1,197,785","173,880","775,102","367,736","209,420","169,013","12,201","16,333","132,802",...,"7,587","7,835","23,865","19,597","1,018","3,250","33,167","22,013","6,569","4,585"
39,1999,"1,272,521","184,280","825,840","397,315","213,173","183,466","12,654","17,509","137,264",...,"8,209","7,870","25,483","21,611",852,"3,020","35,558","23,351","7,357","4,850"
40,2000,"1,365,184","197,580","897,114","436,114","224,829","200,367","13,709","19,082","141,787",...,"7,611","8,014","25,239","21,561",774,"2,904","34,939","22,992","6,837","5,110"
41,2001,"1,482,478","205,825","990,298","477,802","247,686","224,136","15,424","21,083","149,588",...,"7,786","8,518","26,117","22,054",723,"3,340","35,353","23,112","7,063","5,178"
42,2002,"1,630,533","219,435","1,097,569","537,035","265,381","248,022","18,856","22,782","159,874",...,"9,376","9,148","29,230","24,336",873,"4,021","40,207","26,577","8,503","5,127"
43,2003,"1,770,023","235,460","1,195,341","588,671","282,668","268,965","22,224","26,517","176,439",...,"9,674","9,823","31,009","26,034",711,"4,264","42,703","28,181","8,963","5,559"
44,2004,"1,894,161","248,765","1,287,127","625,246","311,122","290,743","24,898","27,951","186,406",...,"10,014","10,531","32,992","27,945",659,"4,388","45,360","29,861","9,355","6,143"
45,2005,"2,026,262","264,965","1,383,057","670,080","339,762","309,351","26,496","29,802","195,456",...,"10,401","11,669","36,041","30,436",681,"4,924","49,171","32,707","9,720","6,745"
46,2006,"2,163,806","278,349","1,484,752","704,389","403,692","306,680","29,765","31,861","206,814",...,"11,709","13,111","41,651","35,244",746,"5,661","50,185","31,772","10,963","7,450"
47,2007,"2,304,160","294,246","1,580,302","747,114","432,749","325,856","32,262","33,198","217,431",...,"12,245","14,921","47,344","39,769","1,014","6,561","56,292","36,701","11,231","8,360"
48,2008,"2,400,950","301,151","1,661,038","767,744","466,969","344,397","34,031","37,686","210,927",...,"13,533","16,138","52,470","44,559",944,"6,967","59,521","37,762","12,589","9,171"
49,2009,"2,491,503","298,232","1,755,973","792,399","498,627","374,709","36,670","42,463","215,906",...,"14,507","15,554","47,595","39,008","1,763","6,824","54,257","32,783","12,744","8,730"
50,2010,"2,588,734","303,421","1,830,207","817,682","519,534","397,425","38,301","45,723","227,283",...,"16,306","15,221","46,788","38,107","2,127","6,554","56,214","33,368","14,179","8,667"
51,2011,"2,676,377","312,304","1,900,677","849,185","544,564","406,797","39,973","48,170","230,222",...,"16,909","16,060","48,076","38,524","2,589","6,963","61,098","37,681","14,320","9,097"
52,2012,"2,784,281","325,074","1,971,573","878,105","568,309","422,783","40,003","49,758","247,286",...,"17,378","16,407","50,168","40,521","2,620","7,027","64,613","40,475","14,758","9,380"
53,2013,"2,859,107","333,801","2,019,966","880,207","588,855","444,981","39,586","52,840","260,771",...,"15,881","17,084","51,407","41,486","2,660","7,261","64,994","41,950","13,221","9,823"
54,2014,"3,010,322","345,400","2,154,894","926,763","617,326","498,214","41,449","57,931","265,731",...,"17,013","16,787","50,420","41,645","2,348","6,427","63,447","38,422","14,665","10,360"
55,2015,"3,177,216","360,681","2,293,717","981,936","647,728","542,995","41,622","64,688","272,481",...,"17,414","16,793","50,549","42,451","2,242","5,856","67,946","41,837","15,172","10,937"
56,2016,"3,324,095","375,394","2,403,044","1,037,028","675,730","564,869","41,190","67,449","286,476",...,"18,292","17,633","50,654","42,577","2,140","5,937","70,770","42,922","16,152","11,696"
57,2017,"3,464,208","385,333","2,497,226","1,081,394","704,948","578,795","41,877","72,134","302,490",...,"18,432","18,468","58,281","50,016","2,091","6,174","74,096","45,461","16,341","12,294"
58,2018,"3,637,678","403,033","2,627,731","1,142,822","751,592","596,795","41,729","76,172","314,480",...,"20,501","19,620","61,940","53,469","2,216","6,255","77,023","45,372","18,285","13,365"
59,2019,"3,805,121","420,412","2,744,967","1,179,333","805,227","615,388","42,811","82,281","332,866",...,"21,511","20,294","64,279","55,848","2,114","6,317","77,510","44,136","19,397","13,977"
60,2020,"4,204,311","412,276","2,847,640","1,184,273","833,827","672,504","43,658","92,169","501,040",...,"23,295","22,174","61,721","52,733","2,021","6,967","77,977","41,497","21,274","15,207"
61,2021,"4,376,932","457,160","3,062,007","1,263,112","894,587","738,064","43,939","99,853","426,019",...,"27,772","24,084","68,106","58,620","2,039","7,447","87,851","45,481","25,733","16,637"
62,2022,"4,586,625","491,924","3,292,037","1,358,610","951,731","809,899","46,103","101,950","369,841",...,"33,887","25,668","64,016","53,497","2,539","7,980","94,568","45,533","31,348","17,688"
63,2023,"4,925,324","525,424","3,614,341","1,511,174","1,037,275","873,681","47,980","119,614","394,117",...,"32,529","27,264","68,426","56,187","3,195","9,044","93,535","45,980","29,334","18,220"
64,2024,"5,278,588","556,554","3,892,868","1,644,592","1,118,000","931,692","50,009","117,580","432,933",...,"33,386","29,562","71,091","57,812","3,388","9,891","97,144","47,475","29,998","19,671"

In [14]:
df.columns.tolist()

['Year',
 'Total National Health Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 '     Public Health Activity',
 '     Investment',
 '         Research',
 '         Structures & Equipment',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'POPULATION',
 'Health Consumption Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 '     Public Health Activity',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Personal Health Care',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Hospital Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Physician and Clinical Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Dental Services Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Other Professional Services Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Home Health Care Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Other Non-Durable Medical Products Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Prescription Drug Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Durable Medical Equipment Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Nursing Care Facilities and Continuing Care Retirement Communities',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Other Health, Residential, and Personal Care Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Total Administration and Total Non-Medical Insurance Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'State and Local  Administration Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Federal Administration Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Non-Medical Insurance Expenditures',
 '     Out of pocket',
 '     Health Insurance',
 '          Private Health Insurance',
 '          Medicare',
 '          Medicaid (Title XIX)',
 '         Department of Defense',
 '         Department of Veterans Affairs',
 '     Other Third Party Payers and Programs',
 '         Worksite Health Care',
 '         Other Private Revenues',
 '         Indian Health Services ',
 "         Workers' Compensation",
 '         General Assistance',
 '         Maternal/Child Health',
 '         Vocational Rehabilitation',
 '         Other Federal Programs*',
 '         SAMHSA',
 '         Other State and Local Programs**',
 '         School Health',
 'Total CMS Programs (Medicaid, CHIP and Medicare)',
 'Public Health Activity',
 '  Federal Funds',
 '  State/Local Funds',
 'Research',
 '     Private ',
 "     Federal Gov't",
 "     State and Local Gov't",
 'Total Structures and Equipment',
 '     Private ',
 "     Federal Gov't",
 "     State and Local Gov't",
 '     Structures',
 '         Private ',
 "         Federal Gov't",
 "         State and Local Gov't",
 '     Equipment',
 '          Private ',
 "          Federal Gov't",
 "          State and Local Gov't"]